session_name: reasonably-typed
windows:
- window_name: build
  layout: main-vertical
  options:
    main-pane-width: 120
  panes:
    - npm run testw
    - npm run buildw
    - code .
environment:
  db_host_env: "localhost"
  db_port_env: "5432"
  db_name_env: throwaway
  db_user_env: throwaway
  db_pass_env: throwaway
