// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function $$catch(prim, prim$1) {
  return prim$1.catch(Curry.__1(prim));
}

function then_(prim, prim$1) {
  return prim$1.then(Curry.__1(prim));
}

function resolve(prim) {
  return Promise.resolve(prim);
}

exports.$$catch = $$catch;
exports.then_ = then_;
exports.resolve = resolve;
/* No side effect */
