// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Js_types = require("bs-platform/lib/js/js_types.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var PromiseFailure = Caml_exceptions.create("ErrorUtil-NirenoReasonablyTyped.PromiseFailure");

function unwrap(_err) {
  while(true) {
    var err = _err;
    var x = err[1];
    var match = Js_types.classify(x);
    if (typeof match === "number") {
      if (match >= 3) {
        return err;
      } else {
        _err = x;
        continue ;
      }
    } else {
      _err = x;
      continue ;
    }
  };
}

exports.PromiseFailure = PromiseFailure;
exports.unwrap = unwrap;
/* No side effect */
