// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Util = require("util");

function set(req, key, value) {
  return (req.session[key] = value);
}

function get(req, key) {
  return (req.session[key]);
}

var save = Util.promisify((function (prim, prim$1) {
        prim.session.save(prim$1);
        return /* () */0;
      }));

exports.set = set;
exports.get = get;
exports.save = save;
/* save Not a pure module */
