// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function makeStore (session,options){
    let pgSimple = require("connect-pg-simple")
    let Store = pgSimple(session)
    return new Store(options)
  };

exports.makeStore = makeStore;
/* No side effect */
