// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Pug = require("pug");
var Util = require("util");

function renderFile(path, options) {
  return Pug.renderFile(path, options);
}

var renderFileAsync = Util.promisify(Pug.renderFile);

function renderFileAsync$1(path, options) {
  return renderFileAsync(path, options);
}

exports.renderFile = renderFile;
exports.renderFileAsync = renderFileAsync$1;
/* renderFileAsync Not a pure module */
