// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Pug = require("pug");
var Util = require("util");

var renderFileAsync = Util.promisify(Pug.renderFile);

exports.renderFileAsync = renderFileAsync;
/* renderFileAsync Not a pure module */
