// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var ErrorUtil$NirenoReasonablyTyped = require("../src/ErrorUtil.bs.js");

var Rejection = Caml_exceptions.create("ErrorUtil_test-NirenoReasonablyTyped.Rejection");

describe("ErrorUtil", (function () {
        return Jest.testPromise("unboxing", undefined, (function (param) {
                      return Promise.reject([
                                        Rejection,
                                        {
                                          code: "ENOENT"
                                        }
                                      ]).catch((function (e) {
                                        return Promise.reject([
                                                    ErrorUtil$NirenoReasonablyTyped.PromiseFailure,
                                                    e
                                                  ]);
                                      })).catch((function (e) {
                                      return Promise.reject([
                                                  ErrorUtil$NirenoReasonablyTyped.PromiseFailure,
                                                  e
                                                ]);
                                    })).catch((function (e) {
                                    return Promise.resolve(Jest.Expect[/* toBe */2]("ENOENT", Jest.Expect[/* expect */0](ErrorUtil$NirenoReasonablyTyped.unwrap(e).code)));
                                  }));
                    }));
      }));

exports.Rejection = Rejection;
/*  Not a pure module */
