// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Flash = require("flash");
var Express = require("bs-express/src/Express.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Superagent = require("superagent");
var ExpressSession = require("express-session");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var ExpressSession$ReasonablyTyped = require("../src/ExpressSession.bs.js");

function listen(app) {
  return new Promise((function (resolve, reject) {
                var onListen = function (e) {
                  var exit = 0;
                  var val;
                  try {
                    val = e;
                    exit = 1;
                  }
                  catch (raw_e){
                    var e$1 = Caml_js_exceptions.internalToOCamlException(raw_e);
                    return reject(e$1);
                  }
                  if (exit === 1) {
                    return resolve("ok");
                  }
                  
                };
                Express.App[/* listen */19](app, 3000, onListen, /* () */0);
                return /* () */0;
              }));
}

var agent = Superagent.agent();

describe("Session", (function () {
        Jest.beforeAllPromise(undefined, (function (param) {
                var app = Express.express(/* () */0);
                Express.App[/* use */0](app, ExpressSession({
                          secret: "secret",
                          resave: false,
                          saveUninitialized: false,
                          cookie: {
                            secure: false
                          }
                        }));
                Express.App[/* use */0](app, Flash());
                Express.App[/* get */4](app, "/test-flash", Express.Middleware[/* from */5]((function (_next, req, res) {
                            req.flash("info", "foo-flash");
                            return Express.Response[/* redirect */14]("/get-flash", res);
                          })));
                Express.App[/* get */4](app, "/get-flash", Express.Middleware[/* from */5]((function (_next, _req, res) {
                            var messages = res.locals.flash;
                            return Express.Response[/* sendString */2](Caml_array.caml_array_get(messages, 0).message, res);
                          })));
                Express.App[/* get */4](app, "/test-state", Express.Middleware[/* from */5]((function (_next, req, res) {
                            ExpressSession$ReasonablyTyped.set(req, "foo", "foo-state");
                            return Express.Response[/* redirect */14]("/get-state", res);
                          })));
                Express.App[/* get */4](app, "/get-state", Express.Middleware[/* from */5]((function (_next, req, res) {
                            var foo = ExpressSession$ReasonablyTyped.get(req, "foo");
                            return Express.Response[/* sendString */2](foo, res);
                          })));
                return listen(app);
              }));
        Jest.testPromise("keeps flash messages available after redirect", undefined, (function (param) {
                return agent.get("http://localhost:3000/test-flash").then((function (response) {
                              var text = response.text;
                              if (text === "foo-flash") {
                                return Promise.resolve(Jest.pass);
                              } else {
                                return Pervasives.failwith("Expected  but got" + text);
                              }
                            }));
              }));
        return Jest.testPromise("keeps session state available after redirect", undefined, (function (param) {
                      return agent.get("http://localhost:3000/test-state").then((function (response) {
                                    var text = response.text;
                                    if (text === "foo-state") {
                                      return Promise.resolve(Jest.pass);
                                    } else {
                                      return Pervasives.failwith("Expected bar but got " + (String(text) + ""));
                                    }
                                  }));
                    }));
      }));

exports.listen = listen;
exports.agent = agent;
/* agent Not a pure module */
