// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Validator = require("validator");

describe("Validator", (function () {
        Jest.test("Is not an email", (function (param) {
                return Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](Validator.isEmail("@example.com")));
              }));
        return Jest.test("Valid email", (function (param) {
                      return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](Validator.isEmail("me@example.com")));
                    }));
      }));

/*  Not a pure module */
